---
- name: Allocating elastic IP to instance
  hosts: localhost
  connection: local
  vars_files:
  - [var.yml]
  tasks:
  - name: association of elastic ip started
    ec2_eip:
      aws_access_key: "{{aws_access_key}}"
      aws_secret_key: "{{aws_secret_key}}"
      region: us-west-1
      ip: current ip address
