---
- name: Create s3 bucket using ansible
  hosts: localhost
  connection: local
  vars_files:
  - [var.yml]
  tasks:
  - name: creation of S3 bucket
    s3_bucket:
      name: myansiblebucketlogs
      region: eu-west-1
      versioning: yes
      state: present
      policy_document: "read_policy.json"
      policy_json: "specific_vpc.json"
      aws_access_key: "{{aws_access_key}}"
      aws_secret_key: "{{aws_secret_key}}"
    register: s3_url

  - name: Enable logging of s3 bucket mywebsite.com to s3 bucket mylogs
    s3_logging:
       name: ansiblebucket_2017
       target_bucket: myansiblebucketlogs
       target_prefix: logs/ansiblebucket_2017
       state: present

  - name: Display s3 url
    debug: var=s3_url
